name: viettire_app
description: Simple Flutter app to capture an image and send it with form data to an n8n webhook.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
